"""add password column to customers

Revision ID: 608b204b1412
Revises: ba6a37d826b7
Create Date: 2026-03-06 15:50:40.547129

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '608b204b1412'
down_revision: Union[str, None] = 'ba6a37d826b7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customers', sa.Column('password', sa.String(length=255), nullable=False, server_default='temp'))
    op.alter_column('customers', 'password', server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('customers', 'password')
    # ### end Alembic commands ###
